kind: pipeline
name: default

volumes:
  - name: webroot
    host:
      path: /root/container-config/www
  - name: pnpm-cache
    host:
      path: /root/container-cache/.pnpm-cache

trigger:
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /drone/src/.pnpm-store
    volumes:
      - name: pnpm-cache
        path: /cache

  - name: build
    image: chiskat/baseline-node20:2026.1.14
    commands:
      - pnpm i
      - pnpm run build
    environment:
      GENERATE_SOURCEMAP: false

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /drone/src/.pnpm-store
    volumes:
      - name: pnpm-cache
        path: /cache

  - name: deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint:
        from_secret: S3_ENDPOINT
      region:
        from_secret: S3_REGION
      bucket:
        from_secret: S3_BUCKET_NAME
      access_key:
        from_secret: S3_ACCESS_KEY_ID
      secret_key:
        from_secret: S3_SECRET_ACCESS_KEY
      source: ./dist/**/*
      target: /paperplane-offwork-time
      strip_prefix: dist

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/offwork/
      - rm -rf /webroot/offwork/*
      - cp -rf ./dist/* /webroot/offwork/
