kind: pipeline
name: default

workspace:
  path: /offwork-time

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  branch:
    - master

steps:
  - name: build
    image: chiskat/baseline-node20:2026.1.14
    volumes:
      - name: pnpm-cache
        path: /offwork-time/.pnpm-store
    commands:
      - pnpm i
      - pnpm run build
    environment:
      GENERATE_SOURCEMAP: false

  - name: deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint:
        from_secret: S3_ENDPOINT
      region:
        from_secret: S3_REGION
      bucket:
        from_secret: S3_BUCKET_NAME
      access_key:
        from_secret: S3_ACCESS_KEY_ID
      secret_key:
        from_secret: S3_SECRET_ACCESS_KEY
      source: ./dist/**/*
      target: /paperplane-offwork-time
      strip_prefix: dist

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/offwork/
      - rm -rf /webroot/offwork/*
      - cp -rf ./dist/* /webroot/offwork/
